### PR TITLE
fix: repeat must not mutate its result object in place (#785)

### LINKED ISSUE #785: <Repeat/> does not update when its times.prop changes
### Describe the bug

```tsx
function Counter() {
  const [count, setCount] = createSignal(2);
  const increment = () => setCount((count) => count + 1);
  const decrement = () => setCount((count) => count - 1);

  return (
    <>
      <button onClick={increment}>increment</button>
      <button onClick={decrement}>decrement</button>
      <Repeat times={count()}>{() => "hallo"}</Repeat>
    </>
  );
}
```

steps to reproduce bug:
- initial render: `hallohallo`
- press decrement: stays `hallohallo`
- press increment: stays `hallohallo`
- only when times becomes 0 it will render empty

[I was able to narrow the bug to the usage of `createMemo` in `<Repeat/>`](https://playground.solidjs.com/anonymous/cfa666cf-17cc-4aca-a091-a19f949bd2a5)

### Minimal Reproduction Link

https://playground.solidjs.com/anonymous/6c6feac1-bd0d-41f1-b6ec-61bca51182e3

### PR DESCRIPTION
**Pull request by webstrand**
Fixes #785

This substantially rewrites `repeat` to be more straight-forward with fewer closures, unlike #786 which is more conservative.

### CODE REVIEW

File: packages/range/src/repeat.ts [hunk 1]
```diff
@@ -23,60 +23,68 @@ export function repeat<T>(
...
+      next[index] = createRoot(dispose => {
+        disposers[index] = dispose;
+        return mapFn(index);
+      });
+    }
 
-  const memoLen = createMemo(() => Math.floor(Math.max(times(), 0)));
-  return () => {
-    const len = memoLen();
-    return untrack(() => {
```
Comment (webstrand) [inline packages/range/src/repeat.ts:75]: I removed this `untrack` call+closure, as far as I can tell it's redundant: `createRoot` already does both Owner and Listener.

**Comment by webstrand** [comment]
This is actually kind of broken still, if the array returned from `repeat()()` is mutated, internal state can be corrupted

**Comment by thetarnav** [comment]
That’s fine
The same probably happens with mapArray and others
When mutating the result one should copy
Nothing broken with that

**Comment by webstrand** [comment]
Is it appropriate to narrow the return type to `readonly T[]` then to signal to users not to mutate the return value?

I've narrowed the return type in the most recent batch of commits, and I've fixed a bug in my implementation and added another test.

I'm not sure if you'd rather have a single commit in the PR or multiple?

**Comment by thetarnav** [comment]
readonly arrays are not allowed by JSX types, so I wouldn't do that.
